CREATE DATABASE hackinions;

USE hackinions;

CREATE TABLE users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(20),
    bio VARCHAR(250),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hackent(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    content VARCHAR(250) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


